name: 'code-style'

on:
  pull_request:
    branches:
      - main

jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4

      - name: 'Lint code with Ruff'
        run: |
          pipx install ruff
          ruff check .

      - name: 'Type cheking with MyPy'
        run: |
          pipx install mypy
          mypy --ignore-missing-imports codelimit/
